# Generated by Django 3.2.9 on 2021-11-17 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toysModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toymodel',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 21, 11, 53, 794730, tzinfo=utc)),
        ),
    ]
