# Generated by Django 3.2.9 on 2021-11-17 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toysModel', '0003_auto_20211117_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toymodel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='toymodel',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 21, 33, 35, 193187, tzinfo=utc)),
        ),
    ]
