# Generated by Django 3.2.9 on 2021-11-18 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toysModel', '0004_auto_20211117_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toymodel',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 1, 47, 40, 591571, tzinfo=utc)),
        ),
    ]
