# Generated by Django 3.2.9 on 2021-11-14 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 21, 9, 59, 427156, tzinfo=utc)),
        ),
    ]
