# Generated by Django 3.2.9 on 2021-11-17 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_alter_toy_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 17, 3, 52, 365274, tzinfo=utc)),
        ),
    ]
