# Generated by Django 3.2.9 on 2021-11-18 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_alter_toy_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 1, 47, 40, 591082, tzinfo=utc)),
        ),
    ]
